[package]
name = "vexel"
version = "0.1.0"
edition = "2021"

[lib]
name = "vexel"
path = "src/lib.rs"

[[bin]]
name = "vexel"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
glob = "0.3.1"
