use crate::utils::marker::Marker;

#[derive(Debug, Clone, PartialEq)]
pub enum JpegLsMarker {
    SOI,
    EOI,
    SOF55,
    SOS,
    LSE,
    DNL,
    DRI,
    RST0,
    RST1,
    RST2,
    RST3,
    RST4,
    RST5,
    RST6,
    RST7,
    APP0,
    APP1,
    APP2,
    APP3,
    APP4,
    APP5,
    APP6,
    APP7,
    APP8,
    APP9,
    APP10,
    APP11,
    APP12,
    APP13,
    APP14,
    APP15,
    COM,
}

impl Marker for JpegLsMarker {
    fn from_u16(value: u16) -> Option<Self> {
        match value {
            0xFFD8 => Some(JpegLsMarker::SOI),
            0xFFD9 => Some(JpegLsMarker::EOI),
            0xFFF7 => Some(JpegLsMarker::SOF55),
            0xFFDA => Some(JpegLsMarker::SOS),
            0xFFF8 => Some(JpegLsMarker::LSE),
            0xFFDC => Some(JpegLsMarker::DNL),
            0xFFDD => Some(JpegLsMarker::DRI),
            0xFFD0 => Some(JpegLsMarker::RST0),
            0xFFD1 => Some(JpegLsMarker::RST1),
            0xFFD2 => Some(JpegLsMarker::RST2),
            0xFFD3 => Some(JpegLsMarker::RST3),
            0xFFD4 => Some(JpegLsMarker::RST4),
            0xFFD5 => Some(JpegLsMarker::RST5),
            0xFFD6 => Some(JpegLsMarker::RST6),
            0xFFD7 => Some(JpegLsMarker::RST7),
            0xFFE0 => Some(JpegLsMarker::APP0),
            0xFFE1 => Some(JpegLsMarker::APP1),
            0xFFE2 => Some(JpegLsMarker::APP2),
            0xFFE3 => Some(JpegLsMarker::APP3),
            0xFFE4 => Some(JpegLsMarker::APP4),
            0xFFE5 => Some(JpegLsMarker::APP5),
            0xFFE6 => Some(JpegLsMarker::APP6),
            0xFFE7 => Some(JpegLsMarker::APP7),
            0xFFE8 => Some(JpegLsMarker::APP8),
            0xFFE9 => Some(JpegLsMarker::APP9),
            0xFFEA => Some(JpegLsMarker::APP10),
            0xFFEB => Some(JpegLsMarker::APP11),
            0xFFEC => Some(JpegLsMarker::APP12),
            0xFFED => Some(JpegLsMarker::APP13),
            0xFFEE => Some(JpegLsMarker::APP14),
            0xFFEF => Some(JpegLsMarker::APP15),
            0xFFFE => Some(JpegLsMarker::COM),
            _ => None,
        }
    }

    fn to_u16(&self) -> u16 {
        match self {
            JpegLsMarker::SOI => 0xFFD8,
            JpegLsMarker::EOI => 0xFFD9,
            JpegLsMarker::SOF55 => 0xFFF7,
            JpegLsMarker::SOS => 0xFFDA,
            JpegLsMarker::LSE => 0xFFF8,
            JpegLsMarker::DNL => 0xFFDC,
            JpegLsMarker::DRI => 0xFFDD,
            JpegLsMarker::RST0 => 0xFFD0,
            JpegLsMarker::RST1 => 0xFFD1,
            JpegLsMarker::RST2 => 0xFFD2,
            JpegLsMarker::RST3 => 0xFFD3,
            JpegLsMarker::RST4 => 0xFFD4,
            JpegLsMarker::RST5 => 0xFFD5,
            JpegLsMarker::RST6 => 0xFFD6,
            JpegLsMarker::RST7 => 0xFFD7,
            JpegLsMarker::APP0 => 0xFFE0,
            JpegLsMarker::APP1 => 0xFFE1,
            JpegLsMarker::APP2 => 0xFFE2,
            JpegLsMarker::APP3 => 0xFFE3,
            JpegLsMarker::APP4 => 0xFFE4,
            JpegLsMarker::APP5 => 0xFFE5,
            JpegLsMarker::APP6 => 0xFFE6,
            JpegLsMarker::APP7 => 0xFFE7,
            JpegLsMarker::APP8 => 0xFFE8,
            JpegLsMarker::APP9 => 0xFFE9,
            JpegLsMarker::APP10 => 0xFFEA,
            JpegLsMarker::APP11 => 0xFFEB,
            JpegLsMarker::APP12 => 0xFFEC,
            JpegLsMarker::APP13 => 0xFFED,
            JpegLsMarker::APP14 => 0xFFEE,
            JpegLsMarker::APP15 => 0xFFEF,
            JpegLsMarker::COM => 0xFFFE,
        }
    }
}

pub static JPEG_LS_MARKERS: [JpegLsMarker; 32] = [
    JpegLsMarker::SOI,
    JpegLsMarker::EOI,
    JpegLsMarker::SOF55,
    JpegLsMarker::SOS,
    JpegLsMarker::LSE,
    JpegLsMarker::DNL,
    JpegLsMarker::DRI,
    JpegLsMarker::RST0,
    JpegLsMarker::RST1,
    JpegLsMarker::RST2,
    JpegLsMarker::RST3,
    JpegLsMarker::RST4,
    JpegLsMarker::RST5,
    JpegLsMarker::RST6,
    JpegLsMarker::RST7,
    JpegLsMarker::APP0,
    JpegLsMarker::APP1,
    JpegLsMarker::APP2,
    JpegLsMarker::APP3,
    JpegLsMarker::APP4,
    JpegLsMarker::APP5,
    JpegLsMarker::APP6,
    JpegLsMarker::APP7,
    JpegLsMarker::APP8,
    JpegLsMarker::APP9,
    JpegLsMarker::APP10,
    JpegLsMarker::APP11,
    JpegLsMarker::APP12,
    JpegLsMarker::APP13,
    JpegLsMarker::APP14,
    JpegLsMarker::APP15,
    JpegLsMarker::COM,
];
